### ISSUE TITLE
Footer 만들기

### ISSUE THREAD

**Issue by KimKyuHoi** [Happy-New-Here/HappyNewHere_FE#10]
- [x] 페이지 넘길 수 있도록 Navigation바 만들기
- [x] 피드, 검색창, 대화창, 마이페이지 만들것(대화창이랑 마이페이지는 막아놓을것.)

**Comment by chae-won-shin** [comment]
제가 footer 맡겠습니다

**Comment by KimKyuHoi** [comment]
css: tailwind
반응형: tailwind css, https://tailwindcss.com/docs/installation 참고

브랜치명 Feat/issue-#10
