### ISSUE TITLE
가입시 아이디 입력 및 상태메세지 입력

### ISSUE THREAD

**Issue by Dobbymin** [Happy-New-Here/HappyNewHere_FE#34]
- [x] #26 이어서 작업하는 issue
- [x]  아이디 설정 입력 form 형식 컴포넌트 구현
- [x] 콘솔 로그에 submitHandler를 찍었을때 정보값 넘어오는 것까지 구현할 것
- [x] 아이디 중복 체크 버튼 구현
- [x] 닉네임 입력하지 않고 페이지 넘어갈려고 할때 유효성체크하기

- [x] Nickname → id 로 파일 이름 변경
- [x] #26 에서 작업한 디자인 적용
- [x] Tailwind css 적용
- [x] id → 필수입력, 상태메세지 → 선택 으로 구현

**Comment by KimKyuHoi** [comment]
이거 좀 감동인디 ㅎ
