### ISSUE TITLE
메시지 목록, 메시지 읽기 컴포넌트 구현

### ISSUE THREAD

**Issue by KimKyuHoi** [Happy-New-Here/HappyNewHere_FE#6]
메시지 목록: 
- [x] 스크롤 형식 구현
- [x] 더미데이터로 메시지 목록 구현

메시지 읽기: 
- [x] Message.jsx의 스타일 재사용 -> 별도의 모듈로 빼기

**Comment by joojjang** [comment]
이것도 저여 메시지 작성을 제가 해서 제가 코드를 알 것 같아수
